package com.dyhx.kdtask.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dyhx.kdtask.db.model.DayTaskMd;
import com.dyhx.kdtask.db.model.HourTaskMd;
import com.dyhx.kdtask.db.model.MinuteTaskMd;

import com.dyhx.kdtask.db.greendao.DayTaskMdDao;
import com.dyhx.kdtask.db.greendao.HourTaskMdDao;
import com.dyhx.kdtask.db.greendao.MinuteTaskMdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dayTaskMdDaoConfig;
    private final DaoConfig hourTaskMdDaoConfig;
    private final DaoConfig minuteTaskMdDaoConfig;

    private final DayTaskMdDao dayTaskMdDao;
    private final HourTaskMdDao hourTaskMdDao;
    private final MinuteTaskMdDao minuteTaskMdDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dayTaskMdDaoConfig = daoConfigMap.get(DayTaskMdDao.class).clone();
        dayTaskMdDaoConfig.initIdentityScope(type);

        hourTaskMdDaoConfig = daoConfigMap.get(HourTaskMdDao.class).clone();
        hourTaskMdDaoConfig.initIdentityScope(type);

        minuteTaskMdDaoConfig = daoConfigMap.get(MinuteTaskMdDao.class).clone();
        minuteTaskMdDaoConfig.initIdentityScope(type);

        dayTaskMdDao = new DayTaskMdDao(dayTaskMdDaoConfig, this);
        hourTaskMdDao = new HourTaskMdDao(hourTaskMdDaoConfig, this);
        minuteTaskMdDao = new MinuteTaskMdDao(minuteTaskMdDaoConfig, this);

        registerDao(DayTaskMd.class, dayTaskMdDao);
        registerDao(HourTaskMd.class, hourTaskMdDao);
        registerDao(MinuteTaskMd.class, minuteTaskMdDao);
    }
    
    public void clear() {
        dayTaskMdDaoConfig.clearIdentityScope();
        hourTaskMdDaoConfig.clearIdentityScope();
        minuteTaskMdDaoConfig.clearIdentityScope();
    }

    public DayTaskMdDao getDayTaskMdDao() {
        return dayTaskMdDao;
    }

    public HourTaskMdDao getHourTaskMdDao() {
        return hourTaskMdDao;
    }

    public MinuteTaskMdDao getMinuteTaskMdDao() {
        return minuteTaskMdDao;
    }

}
